import bcrypt from 'bcryptjs';
const data = {
    users: [{
            name: 'Basir',
            email: 'admin@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true,
        },
        {
            name: 'John',
            email: 'user@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: false,
        },
    ],
    products: [{
            name: 'Valvoline Advanced Full Synthetic SAE 5W-30 Motor Oil 5 QT ',
            category: 'Engine Oil',
            image: '/images/p1.jpg',
            price: 350,
            countInStock: 10,
            brand: 'Nike',
            size: "5 liters",
            rating: 4.5,
            minOrder: 5,
            numReviews: 10,
            priceTag: 400,
            description: 'high quality product',
            unit: 'liter',
        },
        {
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Adidas',
            size: "L",
            minOrder: 4,
            rating: 4.0,
            numReviews: 10,
            priceTag: 140,
            description: 'high quality product',
            unit: 'liter',
        },
        {
            name: 'Lacoste Free Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 220,
            countInStock: 0,
            brand: 'Lacoste',
            size: "XL",
            rating: 4.8,
            minOrder: 10,
            numReviews: 17,
            priceTag: 260,
            description: 'high quality product',
            unit: 'half liter',
        },
        {
            name: 'Nike Slim Pant',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 78,
            countInStock: 15,
            brand: 'Nike',
            size: "M",
            rating: 4.5,
            minOrder: 12,
            numReviews: 14,
            priceTag: 90,
            description: 'high quality product',
            unit: 'liter',
        },
        {
            name: 'Puma Slim Pant',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 65,
            countInStock: 5,
            brand: 'Puma',
            size: "S",
            rating: 4.5,
            minOrder: 5,
            numReviews: 10,
            priceTag: 90,
            unit: 'half',
            description: 'high quality product',

        },
        {
            name: 'Adidas Fit Pant',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            size: "XXL",
            rating: 4.5,
            minOrder: 6,
            numReviews: 15,
            priceTag: 90,
            description: 'high quality product',
            unit: 'half liter',
        },
        {
            name: 'Slim Pant',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 65,
            countInStock: 5,
            brand: 'Puma',
            size: "S",
            rating: 4.5,
            minOrder: 5,
            numReviews: 10,
            priceTag: 90,
            unit: 'half',
            description: 'high quality product',

        },
    ],
};
export default data;